package com.ssl.smarttaskreminder.data.model

import com.google.firebase.Timestamp

/**
 * Firestore Collection: companies
 * Document ID: auto-generated by Firestore (used as cid)
 * Scope: Platform-wide (only Super Admin can read/write)
 */
data class Company(
    val cid: String = "",
    val name: String = "",
    val slug: String = "",
    val industry: String = "",
    val status: String = "active",   // active | inactive
    val createdAt: Timestamp? = null
) {
    /** Converts this model to a Firestore-compatible Map for save operations. */
    fun toMap(): Map<String, Any?> = mapOf(
        "cid"       to cid,
        "name"      to name,
        "slug"      to slug,
        "industry"  to industry,
        "status"    to status,
        "createdAt" to createdAt
    )

    val isActive: Boolean get() = status == "active"
}
