package com.ssl.smarttaskreminder.data.model

import com.google.firebase.Timestamp
import com.ssl.smarttaskreminder.AppConstants
import java.util.Date

/**
 * Firestore Collection: tasks
 * Document ID: auto-generated by Firestore
 * companyId is MANDATORY on EVERY query — no exceptions.
 */
data class Task(
    val documentId: String = "",       // Firestore auto-ID
    val tid: Int = 0,                  // Sequential within company
    val companyId: String = "",        // 🔑 Tenant isolation key — MANDATORY
    val taskName: String = "",
    val styleNo: String = "",
    val details: String = "",
    val importance: String = AppConstants.IMPORTANCE_MEDIUM,  // high | medium | low
    val deadline: Timestamp? = null,
    val createdBy: String = "",        // Firebase UID of creator
    val managerId: Int = 0,            // mid of responsible manager (0 if none)
    val status: String = AppConstants.STATUS_PENDING,         // pending | overdue | completed
    val createdDate: Timestamp? = null,
    val completedAt: Timestamp? = null,
    val completionType: String? = null  // on-time | late | null
) {
    fun toMap(): Map<String, Any?> = mapOf(
        "tid"            to tid,
        "companyId"      to companyId,
        "taskName"       to taskName,
        "styleNo"        to styleNo,
        "details"        to details,
        "importance"     to importance,
        "deadline"       to deadline,
        "createdBy"      to createdBy,
        "managerId"      to managerId,
        "status"         to status,
        "createdDate"    to createdDate,
        "completedAt"    to completedAt,
        "completionType" to completionType
    )

    /** Returns true if the deadline has passed and task is not completed — should be overdue. */
    fun isDeadlinePassed(): Boolean {
        val deadlineDate = deadline?.toDate() ?: return false
        return Date() > deadlineDate && status != AppConstants.STATUS_COMPLETED
    }

    /** Returns how many days are left until the deadline (negative if overdue). */
    fun daysLeft(): Long {
        val deadlineDate = deadline?.toDate() ?: return 0
        val diff = deadlineDate.time - System.currentTimeMillis()
        return diff / (1000 * 60 * 60 * 24)
    }
}
